services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: hris
      POSTGRES_USER: hris_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "password"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/hris
      KC_DB_USERNAME: hris_user
      KC_DB_PASSWORD: password
      KC_HTTP_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://hris_user:password@postgres:5432/hris
      REDIS_URL: redis://:password@redis:6379
      JWT_SECRET: replace-me-with-a-long-random-secret
      KEYCLOAK_JWKS_URI: http://keycloak:8080/realms/hris/protocol/openid-connect/certs
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - keycloak

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    ports:
      - "3001:3000"
    depends_on:
      - api

  worker:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: development
      RUN_MODE: worker
      DATABASE_URL: postgresql://hris_user:password@postgres:5432/hris
      REDIS_URL: redis://:password@redis:6379
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:

